### ISSUE TITLE
[Technical] Spike backend

### ISSUE THREAD

**Issue by Castau** [Hold-Krykke/3SemProject_BackEnd#6]
* Java backend architecture discussion
  * What facades, layers and classes are needed?
  * Do we store data, and how?
  * What does the endpoints return?
  * Is anything called by the frontend or does the backend handle all API calls?
  * How are the many different country maps handled? 
    * Should they be stored in a database or handled by the frontend? Or a third option?

**Comment by MalteMagnussen** [comment]
> Is anything called by the frontend or does the backend handle all API calls?

I think our frontend should only call our backend. So backend acts as our proxy.

**Comment by MrHardcode** [comment]
* Java backend architecture discussion
  * What facades, layers and classes are needed?
Packages:
dto (used to map JSON from other servers)
errorhandling
facades
rest
(if more userstories that require database, login etc. are chosen by the PO, then the relevant packages will be created accordingly)

  * Do we store data, and how?
No, unless we get time to implement extra features such as statistics 

  * What does the endpoints return?
The endpoints return JSON, "customized" to include only the relevant data needed in the frontend

  * Is anything called by the frontend or does the backend handle all API calls?
The frontend should make calls to our own backend and maybe the other group's backend(ChokoBananen) but not to any other servers.

  * How are the many different country maps handled? 
I don't know what the best solution is yet. 

    * Should they be stored in a database or handled by the frontend? Or a third option?
I think we should try to handle the map with countries and cities without saving anything. Hopefully the different countries can be "pulled out" from the original SVG map so we don't need any extra data.

**Comment by Runi-VN** [comment]
Java backend architecture discussion
> What facades, layers and classes are needed?  

- Already covered. (I'm writing this after pushing #7)
  - Also CORS

>Do we store data, and how?
- Not for current user stories

>What does the endpoints return?
- DTOs which hold relevant data *served* in JSON format

>Is anything called by the frontend or does the backend handle all API calls?
- Our backend should work as a proxy and feed our frontend with API-endpoints. (**Utilize Swagger**)
  - Maybe the group *Chokobananens* api should be handled by frontend. I think I prefer that.

>How are the many different country maps handled?
- In my order of preference: 
  1. Framework/Library
  2.  SVGs and SVG-childs
  3. Ticketmaster Map Widget

>Should they be stored in a database or handled by the frontend? Or a third option?
- If we go by SVGs we should preferably find an API that we can access onclick
- Otherwise no storage.

**Comment by MalteMagnussen** [comment]
> What does the endpoints return?

What endpoints, specifically, do we call?

**Comment by Castau** [comment]
*  What facades, layers and classes are needed?
Facades for each endpoint and a Interface they all implement could be a nice thing?

* Do we store data, and how?
No, only when the server is running should data be stored in an object (the cities). 

* What does the endpoints return?
Unsure what is allowed. If objects are allowed, is it only DTO's? Or is it only Json that's the acceptable return?

* Is anything called by the frontend or does the backend handle all API calls?
I prefer that the backend makes all the API calls, including Chokobananens. So we can errorhandle correctly, and form the data as we like. 

* How are the many different country maps handled?
Hopefully countries can be taken from the europe svg, so we only need that one. 

* Should they be stored in a database or handled by the frontend? Or a third option?
No storage.

**Comment by MalteMagnussen** [comment]
To summarize:

1. What facades, layers and classes are needed?
   * Atm we have what we need. Not sure I understand what is meant by Camilla though. 

2. Do we store data, and how?
   * No. In the sense that we don't use SQL. We only have in memory storage. (The cities.)

3. What does the endpoints return?
   * JSON

4. Is anything called by the frontend or does the backend handle all API calls?
   * Our frontend may only call our backend and Chokobananens backend. 

5. How are the many different country maps handled?
   * So far SVG. Asger is still figuring it out, afaik. Maybe a framework? Awaiting Asgers verdict. 

6. Should they be stored in a database or handled by the frontend? Or a third option?
   * No storage.
